# docker run -d --rm -name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq-fy
    restart: unless-stopped
    
  logservice_postgredb:
    image: 'postgres'
    ports:
      - "6011:5432"
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: default_database 
    volumes:
      - ./db-data/logservice:/var/lib/postgresql/data
    restart: unless-stopped
    
  authservice_user_postgredb:
    image: 'postgres'
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - "6013:5432"
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: default_database 
    volumes:
      - ./db-data/authservice_user:/var/lib/postgresql/data
    restart: unless-stopped
      
  authservice_userCache_redis:
    image: "redis:alpine"
    
    command: redis-server
    
    ports:
      - "6023:6379"
    
    volumes:
      - ./db-data/authservice_userCache/www:/home/distressedpro/public_html
      - ./db-data/authservice_userCache/conf:/etc/apache2/sites-available
      
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped

  memberservice_userCache_redis:
    image: "redis:alpine"

    command: redis-server

    ports:
      - "6014:6379"

    volumes:
      - ./db-data/authservice_redis/www:/home/distressedpro/public_html
      - ./db-data/authservice_redis/conf:/etc/apache2/sites-available

    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped

volumes:
  rabbitmqdata:
    driver: local


