# docker run -d --rm -name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: "3.8"

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq-fy

volumes:
  rabbitmqdata:
    driver: local
